Supplier edit 2
jacildoaldrin/tpc_inventory_frontend pull request #62
Opened 2020-11-04 20:42 UTC by lilianyangc

2020-11-04 21:00 UTC, victafrancis requested changes

2020-11-04 21:00 UTC, victafrancis commented on src/components/Forms/EditSupplier/EditSupplier.js
> +                    <InputField
same as add supplier hehe

2020-11-04 21:06 UTC, lilianyangc commented on src/components/Forms/EditSupplier/EditSupplier.js
> +                    <InputField
Oh, missed that part. Thanks!

2020-11-04 22:48 UTC, jacildoaldrin approved these changes

2020-11-04 22:54 UTC, victafrancis approved these changes

2020-11-05 02:31 UTC, AshenCat approved these changes

2020-11-05 02:32 UTC, merged